#!/usr/bin/env bash

echo "Setting up shared environment"

export APP_NAME=quadrant-acquired-conditions
export ZipkinURL=$ZipkinURL
export interopioLoggingURL=$interopioLoggingURL
export appInfo=$appInfo
export AUTO_LOGOUT_MINS=$AUTO_LOGOUT_MINS
export DATA_STORE_URL=$DATA_STORE_URL
export CLIENT_ID=$CLIENT_ID
export CLIENT_SECRET=$CLIENT_SECRET
export CLIENT_LAUNCH_OVERRIDES=$CLIENT_LAUNCH_OVERRIDES
export SCOPE=$SCOPE
export SESSION_SECRET=$SESSION_SECRET
export ALLOWED_IO_ACCOUNTS=$ALLOWED_IO_ACCOUNTS
export ALLOWED_TOKEN_ISS=$ALLOWED_TOKEN_ISS
export UPDATE_CRON_CONFIG=$UPDATE_CRON_CONFIG
export REDIS_URL=$REDIS_URL
export REDIS_CLUSTER_URL=$REDIS_CLUSTER_URL
export REDIS_CLUSTER_PORT=$REDIS_CLUSTER_PORT
export QUADRANT_API_URL=$QUADRANT_API_URL
export QUADRANT_API_TOKEN_URL=$QUADRANT_API_TOKEN_URL
export QUADRANT_API_CLIENT_ID=$QUADRANT_API_CLIENT_ID
export QUADRANT_API_CLIENT_SECRET=$QUADRANT_API_CLIENT_SECRET
export QUADRANT_API_AUDIENCE=$QUADRANT_API_AUDIENCE
export STORAGE_TYPE=$STORAGE_TYPE

export consoleLogLevel=info
export ioLogLevel=silent

echo "CLUSTER: $CLUSTER"
echo "APP_NAME: $APP_NAME"
echo "ZipkinURL: $ZipkinURL"

